name: shamo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  http: ^0.13.3
  get: 4.6.5
  flutter: 
    sdk: flutter
  cloud_firestore: ^4.3.1
  firebase_core: ^2.4.1

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
  - assets/shoes/

