// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpMyz4ZXMvUphbmDRv3UBvpCq50xBrtm8',
    appId: '1:170661524527:web:0fa7db5ef780dea87f82da',
    messagingSenderId: '170661524527',
    projectId: 'shamoapp',
    authDomain: 'shamoapp.firebaseapp.com',
    storageBucket: 'shamoapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsmiiIbgDdBGlGUzuTZ-SwzHOdArLrioY',
    appId: '1:170661524527:android:18a620b717a9989c7f82da',
    messagingSenderId: '170661524527',
    projectId: 'shamoapp',
    storageBucket: 'shamoapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfyxicQQGGuX53H3X3hNgoWpbutqQKqpA',
    appId: '1:170661524527:ios:3ed8f7e201b85eff7f82da',
    messagingSenderId: '170661524527',
    projectId: 'shamoapp',
    storageBucket: 'shamoapp.appspot.com',
    iosClientId: '170661524527-7e445a31853rn69741f0plrg6etl5pmt.apps.googleusercontent.com',
    iosBundleId: 'com.shamoapp.shamoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfyxicQQGGuX53H3X3hNgoWpbutqQKqpA',
    appId: '1:170661524527:ios:3ed8f7e201b85eff7f82da',
    messagingSenderId: '170661524527',
    projectId: 'shamoapp',
    storageBucket: 'shamoapp.appspot.com',
    iosClientId: '170661524527-7e445a31853rn69741f0plrg6etl5pmt.apps.googleusercontent.com',
    iosBundleId: 'com.shamoapp.shamoApp',
  );
}
